### ISSUE TITLE
styling is not looking good on phones..

### ISSUE THREAD

**Issue by soliloquizin** [soliloquizin/ng-choices#5]
Footer:

- right part of footer is wrapped, shouldn't be

~~Home:~~

- ~~width is too big for phones~~
- ~~footer looks misplaced since it's not at the bottom~~

~~Game:~~

- ~~since you need to adapt the zoom, the text and the x are a bit small~~
- ~~Money-value is next to the word but the other values are in the line below~~
- ~~the overlay of the modal is only partially covering the screen, the modal itself is too wide~~
- ~~footer looks misplaced since it's not at the bottom~~

~~Game-Over:~~

- ~~footer looks misplaced since it's not at the bottom~~

**Comment by corneliapelech** [comment]
Footer is actually at the bottom, just looks weird because of the phone-scrolling.

**Comment by soliloquizin** [comment]
fixed most issues, stat-looks will be changed later when icons are introduced
